version: "3.8"
services:
    server:
        #image: 'nginx:stable-alpine'
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - '8000:80'        
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/html
        depends_on:
            - php
            - mysql
            - phpmyadmin

    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated

    mysql:
        image: mysql:5.7
        env_file:
            - ./env/mysql.env    

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html

    zsh:
        build:
            context: ./dockerfiles
            dockerfile: zsh.dockerfile
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
        entrypoint: ["zsh"]

    npm-debug:
        build:
            context: ./dockerfiles
            dockerfile: zsh.dockerfile 
        working_dir: /root/.npm/_logs
        volumes:
            - ./log:/root/.npm/_logs
        entrypoint: ["zsh"]

    artisan:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - ./src:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]    

    npm:
        image: node:14-alpine
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes: 
            - ./src:/var/www/html
            - ./node_modules
            - ./log:/root/.npm/_logs

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.4
        container_name: phpmyadmin
        environment:
           - PMA_ARBITRARY=1
           - PMA_HOST=mysql
        restart: always
        ports:
           - 8080:80
        volumes:
           - /sessions

        env_file:
            - ./env/mysql.env    
        #izphpmyadmin:
        #image: phpmyadmin/phpmyadmin:5.0.4-fpm
        #build:
        #     context: ./phpmyadmin
        #     dockerfile : phpmyadmin.dockerfile
        #container_name: phpmyadmin
        #restart: always
        #depends_on:
        #    - mysql
        #environment:
        #    - PMA_HOST=mysql
        #    - PMA_ARBITRARY=1
        #ports:
        #    - '8080:80'
        #volumes:
        #   - /sessions
